GET http://localhost:8000/users
Authorization: Token 32fc37b6871710de77f9c1fe993f1e1f3889ce25


###
POST http://localhost:8000/auth/signin
Content-Type: application/json

{
    "username": "admin",
    "password": "Data@123!"
}