# Generated by Django 5.0.1 on 2024-03-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
