# Generated by Django 5.0.1 on 2024-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_first_name_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersacco',
            name='is_vetter',
            field=models.BooleanField(default=False),
        ),
    ]
