# Generated by Django 5.0.1 on 2024-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_candidate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('user', 'election'), name='unique_election_candidacy'),
        ),
    ]
