# Generated by Django 5.0.1 on 2024-04-02 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_candidate_unique_election_candidacy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='ElectionCandidate',
        ),
        migrations.RenameModel(
            old_name='UserSacco',
            new_name='SaccoUser',
        ),
        migrations.CreateModel(
            name='Vetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoteActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='electioncandidate',
            name='unique_election_candidacy',
        ),
        migrations.RemoveField(
            model_name='electioncandidate',
            name='user',
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='sacco_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.saccouser'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='electioncandidate',
            constraint=models.UniqueConstraint(fields=('sacco_user', 'election'), name='unique_election_candidacy'),
        ),
        migrations.AddField(
            model_name='vetting',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_vettings', to='base.saccouser'),
        ),
        migrations.AddField(
            model_name='vetting',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.election'),
        ),
        migrations.AddField(
            model_name='vetting',
            name='vetter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetter_vettings', to='base.saccouser'),
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.electioncandidate'),
        ),
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.election'),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.election'),
        ),
        migrations.AddField(
            model_name='voteactivity',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.saccouser'),
        ),
        migrations.AddConstraint(
            model_name='vetting',
            constraint=models.UniqueConstraint(fields=('vetter', 'candidate', 'election'), name='unique_election_candidacy_vetting'),
        ),
    ]
