# Generated by Django 5.0.1 on 2024-04-08 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_customuser_ci_unique_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetting',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_vettings', to='base.electioncandidate'),
        ),
    ]
